= POC Apache OFBiz® plugin for REST

This draft implementation helps to expose existing or new OFBiz services as REST. To facilitate this, added a new "verb" attribute to service elements that helps to determine how a particular service can be accessed via REST.
Those changes are here : https://github.com/girishvasmatkar/ofbiz-framework/tree/feature/add-service-verb

==== Important URLs
* API https://localhost:8443/rest
* WADL https://localhost:8443/rest/application.wadl

==== Endpoints
Once deployed, following URLs can be accessed

* GET /rest/services
* GET /rest/services/{serviceName}?inParams=<URLEncodedJSON> 
* POST /rest/services/{serviceName} (For this endpoint, the service in parameters must be part of Request Body)

==== Authentication
All three demo endpoints are secured. Authentication scheme is "Bearer <JWT>". Every request to the three API endpoints must have an Authorization header associated with it. 
Example -

GET /rest/services HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBcGFjaGVPRkJpeiIsImlhdCI6MTU0NzczOTM0OCwiZXhwIjoxNjc5Mjc1MzQ4LCJhdWQiOiJ3d3cuZXhhbXBsZS5jb20iLCJzdWIiOiJqcm9ja2V0QGV4YW1wbGUuY29tIiwiR2l2ZW5OYW1lIjoiSm9obm55IiwiU3VybmFtZSI6IlJvY2tldCIsIkVtYWlsIjoianJvY2tldEBleGFtcGxlLmNvbSIsInVzZXJMb2dpbklkIjoiYWRtaW4iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.fwafgrgpodBJcXxNTQdZknKeWKb3sDOsQrcR2vcRw97FznD6mkE79p10Tu7cqpUx7LiXuROUAnXEgqDice-BSg
